name: drones
favicon: null
layout_spectrum: 0.6043921646196395
typography_spectrum: 0.38425
title: 'News and info about commercial drone technology: UAV, SUAS, Dronetech'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-65881808-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc143b'
    - '#ffffff'
    - '#f09baa'
    - '#e8687f'
    - '#f4b4c0'
  brandStrength: 0.1082199364900589
  lightness: 0.4302779478020966
  saturation: 0.30516558629460633
  rhythmicContrast: 0.3181922994554043
purpose: []
