name: drones
favicon: null
layout_spectrum: 0.6043921646196395
typography_spectrum: 0.04126006364822388
title: 'News and info about commercial drone technology: UAV, SUAS, Dronetech'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1082199364900589
  lightness: 0.4302779478020966
  saturation: 0.30516558629460633
  rhythmicContrast: 0.3181922994554043
purpose: []
